### ISSUE TITLE
Build failed for version 19.7.6

### ISSUE THREAD

**Issue by FK22222** [microsoftconnect/ms-intune-app-sdk-ios#499]
**Describe the bug:**

We updated the MAUI Intune SDK Package from version 19.7.5 to 19.7.6, which then resulted in the following build error:

> ##[error]CSC(0,0): Error CS1705: Assembly 'Microsoft.Intune.Maui.Essentials.iOS' with identity 'Microsoft.Intune.Maui.Essentials.iOS, Version=19.7.6.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.iOS, Version=18.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=17.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

The lowest possible Microsoft.iOS version with 18.x is 18.0.8303, if you use this you get the following warning and many errors like this:

> ##[warning]ILLINK(0,0): Warning MT0079: The recommended Xcode version for Microsoft.iOS 18.0.8303 is Xcode 16.0 or later. The current Xcode version (found in /Applications/Xcode_15.2.app/Contents/Developer) is 15.2.

> ##[error]/Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UITextView.g.cs(3343,0): Error MT4162: The type 'UIKit.UITextFormattingViewController' (used as a parameter in UIKit.UITextView/_UITextViewDelegate.DidBeginFormatting) is not available in iOS 17.2 (it was introduced in iOS 18.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode).

19.7.6 must be built with XCode 15.X see:

https://learn.microsoft.com/en-us/mem/intune/fundamentals/in-development#take-action-update-to-the-latest-intune-app-sdk-for-ios-and-intune-app-wrapping-tool-for-ios
> For apps built with XCode 15 use v19.7.6 - Release 19.7.6 

https://github.com/microsoftconnect/ms-intune-app-sdk-ios/releases/tag/19.7.6
> This version is intended for applications compiled with Xcode 15. App developers should NOT integrate this version if compiling with Xcode 16 and should instead integrate the latest 20.x release.

As a test, we then started a build with XCode 16.0, it ran through, but as expected the SDK integration no longer works.

**Build Agent:**

We use the Azure DevOps Agents, and we initially set the following versions:
* MacOS: 13
* XCode: 15.2
* Microsoft.iOS: 17.2.8004

I would expect to be able to build the latest Microsoft.Intune.Maui.Essentials.iOS with the most up to date toolchain or at least 19.7.6 with Microsoft.iOS 17.x so that you can build with XCode 15.X.
How do we get out of this version chaos? When will version 20.x be released for MAUI?

**Comment by wangxiaoms** [comment]
Hi Microsoft.Intune.Maui.Essentials.iOS version 20.2.1 has been released, can you try that.

**Comment by FK22222** [comment]
@wangxiaoms Thanks for the quick answer and providing Microsoft.Intune.Maui.Essentials.iOS version 20.2.1. With this version we can build and the SDK integration works again.

Unfortunately, we have more problems with the newer versions than we hoped for, for example, the MSAL interactive login no longer works, unfortunately I won't be able to analyze why until next week.

Is it perhaps possible to make version 19.7.6 available without the unresolvable dependencies?

**Comment by FK22222** [comment]
Sorry, I think that was misunderstood, we no longer have known problems with the SDK. In order to increase the versions of XCode & Microsoft iOS we have to make more adjustments than we thought, but there won't be time for that this year. We would therefore like to have released another update with SDK 19.7.6 and the old XCode & Microsoft iOS (15.x & 17.X) versions.

For our planning, we just need to know whether we will get a version 19.7.x without these version problems, or not?

**Comment by wangxiaoms** [comment]
Hi @FK22222 this issue in Xcode 15 release should be fixed in version 19.7.6.1.
https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.iOS/19.7.6.1

**Comment by FK22222** [comment]
@wangxiaoms thank you very much, with this version the builds are running again!
